### ISSUE TITLE
hardcoded temp vs temp_path

### ISSUE THREAD

**Issue by dmd** [rovest/Bear-Markdown-Export#12]
Should `temp_path` be used here instead of a hardcoded `$HOME/temp` ?

https://github.com/rovest/Bear-Markdown-Export/blob/9701128263c50f484ddfd5b04521f0a207b21e8b/bear_export_sync.py#L117-L118

**Comment by dmd** [comment]
It just seems odd to me to have a hardcoded path when there's a variable seemingly specifically for this.

In general I'd *really* like to see you merge the stuff from @motin !

**Comment by motin** [comment]
@dmd This particular change seem to have been fixed by @rovest in the latest changes in this repository, and it is also fixed in https://github.com/rovest/Bear-Markdown-Export/pull/9, but given https://github.com/rovest/Bear-Markdown-Export/issues/13, we will probably not see that PR merged anytime soon. You can choose what fork to use - I'll continue working on https://github.com/motin/Bear-Markdown-Export meanwhile.

**Comment by rovest** [comment]
Sorry @dmd , I misunderstood the issue. 

You are right, that was odd and an oversight by me.

It's now fixed in v. 1.7.5

CC: @motin
