### ISSUE TITLE
interprets hashbangs as tags

### ISSUE THREAD

**Issue by dmd** [rovest/Bear-Markdown-Export#5]
If I have something in a note that looks like this:

```
#!/usr/bin/python
print("hello")
```

Bear is smart enough not to create a tag called `!/usr/bin/python`, but the sync script isn't, and puts this note in `BearNotes/!/usr/bin/python`

**Comment by dmd** [comment]
It looks like this is an issue with `pattern1` or `pattern2` in `sub_path_from_tag`, but my regex-fu isn't good enough to fix it without breaking something else.

**Comment by rovest** [comment]
Hi @dmd and @motin

This issue should be fixed in Version 1.7.2 - 2018-11-18 released today.

Put your code in a code block or in `back tick code tags` 

It may still be an issue if in normal text, but will look into that as well later on.

My regex-fu is't that good either, the patterns used are based on a lot of trial and error with the help of the excellent [regex101.com](https://regex101.com) web site :)
